# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Birds of Marshside
email: nqzva@oveqfbsznefufvqr.hx
description: > # this means to ignore newlines until "baseurl:"
  An annotated checklist of the of the bird species 
  that have been recorded within and/or from the recording area of Marshside RSPB Reserve.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username: dtylr/bom

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
